/* This file is automatically generated
   do not edit this file directly! */

#ifndef KAIRA_PROJECT_sieve
#define KAIRA_PROJECT_sieve
#include <cailie.h>
#include <algorithm>
#include <stdlib.h>
#include <stdio.h>
#include <sstream>

struct param
{
	static ca::ParameterInt N;
};

#line 1 "*head"

struct Segment{
	std::vector<bool> marks;
	int start;
};


namespace ca {
	
	CA_TOKEN_NAME(Segment, segment) {
		std::stringstream s;
		s << "[" << segment.start << "," << segment.start + segment.marks.size() - 1 << "]";
		for (int i = 0; i < segment.marks.size(); i++) {
			if (segment.marks[i]) {
				s << " " << segment.start + i;
			}
		}
		return s.str();
	}
}

#endif // KAIRA_PROJECT_sieve
