/* This file is automatically generated
   do not edit this file directly! */

#ifndef KAIRA_PROJECT_workers
#define KAIRA_PROJECT_workers
#include <cailie.h>
#include <algorithm>
#include <stdlib.h>
#include <stdio.h>
#include <sstream>

struct param
{
	static ca::ParameterInt LIMIT;
	static ca::ParameterInt SIZE;
};

#line 1 "*head"

struct Job {
	Job() {};
	Job(int start, int end) : start(start), end(end) {}
	int start;
	int end;

	void pack(ca::Packer &p) const {
		p << start << end;
	}

	void unpack(ca::Unpacker &p) {
		p >> start >> end;
	}
	
	std::string token_name() const {
		std::stringstream s;
		s << "Job [" << start << "," << end << ")";
		return s.str();
	}
};

Job jj;





#endif // KAIRA_PROJECT_workers
