/* This file is automatically generated
   do not edit this file directly! */

#ifndef KAIRA_PROJECT_project1
#define KAIRA_PROJECT_project1
#include <cailie.h>
#include <algorithm>
#include <stdlib.h>
#include <stdio.h>
#include <sstream>

struct param
{
};

#line 1 "*head"
int testing;
double aaaaaa;
int AAA;
struct tt
{
tt()
{

}
tt(int x)
{

}

};

class myvar
{
public:
myvar()
{

}
float sum(float x,float y)
{
return x+y;
}
int sum(int x,int y)
{
return x+y;

}

std::string token_name() const
{
return "myvar";
}
char * test()
{

return (char*)"aloha";
}
};

myvar glob;

#endif // KAIRA_PROJECT_project1
