/* This file is automatically generated
   do not edit this file directly! */

#ifndef KAIRA_PROJECT_project1
#define KAIRA_PROJECT_project1
#include <cailie.h>
#include <algorithm>
#include <stdlib.h>
#include <stdio.h>
#include <sstream>

struct param
{
};

#line 1 "*head"


int abc;
double aaaaaa;
int AAA;
struct tt
{
tt()
{

}

};

class myvar
{
public:
myvar()
{

}
std::string token_name() const
{
return "myvar";
}
char * test()
{

return (char*)"aloha";
}
};

myvar glob;


void calib_init(int argc, char **argv);
void project1();
#endif // KAIRA_PROJECT_project1
