/* This file is automatically generated
   do not edit this file directly! */

#ifndef KAIRA_PROJECT_project1
#define KAIRA_PROJECT_project1
#include <cailie.h>
#include <algorithm>
#include <stdlib.h>
#include <stdio.h>
#include <sstream>

struct param
{
};

#line 1 "*head"

#include <iostream>
 

#endif // KAIRA_PROJECT_project1
